# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StockClient
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'StockClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'StockClient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StockClient-tvOS

  target 'StockClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
